# Does not inherit from simplemob MobIfritGuardian
- type: entity
  abstract: true
  name: Голопаразит рыцаря звездной пыли
  id: MobGuardianBaseK
  description: guardian
  save: false
  components:
    - type: LagCompensation
    - type: GhostRole
      allowMovement: true
      allowSpeech: true
      makeSentient: true
      name: Голопаразит рыцаря звездной пыли
      description: Выполняйте приказы своего хозяина
      isBlockedByAntagManager: true
    - type: GhostTakeoverAvailable
    - type: Input
      context: "human"
    - type: MobMover
    - type: InputMover
    - type: MovementSpeedModifier
      baseWalkSpeed: 4
      baseSprintSpeed: 5.5
    - type: DamageOnHighSpeedImpact
      damage:
        types:
          Blunt: 5
      soundHit:
        path: /Audio/Effects/hit_kick.ogg
    - type: RandomSprite
      available:
        - enum.DamageStateVisualLayers.Base:
            miner_base: ""
          enum.DamageStateVisualLayers.BaseUnshaded:
            miner_flare: Sixteen
    - type: Sprite
      drawdepth: Mobs
      sprite: FireStation/Mobs/Security/guardiansKnight.rsi
      netsync: false
      layers:
        - state: miner_base
          map: [ "enum.DamageStateVisualLayers.Base" ]
        - state: miner_flare
          map: [ "enum.DamageStateVisualLayers.BaseUnshaded" ]
          shader: unshaded
      noRot: true
    - type: Clickable
    - type: InteractionOutline
    - type: Physics
      bodyType: KinematicController
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeCircle
            radius: 0.35
          density: 25
          mask:
            - FlyingMobMask
          layer:
            - FlyingMobLayer
    - type: Damageable
      damageContainer: Biological
    - type: MobState
      allowedStates:
        - Alive
    - type: HeatResistance
    - type: CombatMode
    - type: Internals
    - type: Examiner
    - type: Speech
    - type: TypingIndicator
      proto: guardian
    - type: Pullable
    - type: MeleeWeapon
      hidden: true
      angle: 30
      animation: WeaponArcFist
      attackRate: 1.5
      damage:
        types:
          Blunt: 20
    - type: Actions
    - type: Guardian
    - type: InteractionPopup
      interactSuccessString: petting-success-holo
      interactFailureString: petting-failure-holo
      successChance: 0.7
    - type: Tag
      tags:
        - CannotSuicide

#MobGuardianBase
# From the uplink injector
- type: entity
  name: Голопаразит рыцаря звездной пыли
  id: MobHoloparasiteGuardianK
  parent: MobGuardianBaseK
  description: A mesmerising whirl of hard-light patterns weaves a marvelous, yet oddly familiar visage. It stands proud, tuning into its owner's life to sustain itself.
  components:
    - type: GhostRole
      allowMovement: true
      allowSpeech: true
      makeSentient: true
      name: Голопаразит рыцаря звездной пыли
      description: Выполняйте приказы своего хозяина
      isBlockedByAntagManager: true
    - type: GhostTakeoverAvailable
    - type: NameIdentifier
      group: Holoparasite
    - type: TypingIndicator
      proto: holo
    - type: Sprite
      layers:
        - state: miner_base
          map: [ "enum.DamageStateVisualLayers.Base" ]
        - state: miner_flare
          map: [ "enum.DamageStateVisualLayers.BaseUnshaded" ]
          shader: unshaded

