- type: job
  id: SecurityKnight
  name: Рыцарь Звёздной-пыли
  description: Рыцарь
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityKnight
      time: 7200
  startingGear: SecurityKnightGear
  icon: "KnightofStardust"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External

- type: startingGear
  id: SecurityKnightGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitKnight
    back: ClothingBackpackSecurity_KnightFilled
    shoes: ClothingShoesBootsCombatKnight
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHelmetHelmetKnight
    outerClothing: ClothingOuterCoatKnight
    id: Security_KnightPDA
    ears: ClothingHeadsetAltSecurity
    gloves: ClothingHandsGlovesCombat
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtSec
  satchel: ClothingBackpackSecurity_KnightFilled
  duffelbag: ClothingBackpackSecurity_KnightFilled
  pocket1: HoloprojectorSecurity
  pocket2: Flash

- type: entity
  parent: ClothingShoesStorageBase
  id: ClothingShoesBootsCombatKnight
  name: Туфли Звёздной-пыли
  description: Необычно бизарные туфли, имеющие необычно бизарные свойства.
  components:
  - type: Sprite
    sprite: Clothing/Shoes/Boots/laceups.rsi
  - type: Clothing
    sprite: Clothing/Shoes/Boots/laceups.rsi
  - type: StorageFill
    contents:
    - id: CombatKnife

- type: entity
  parent: BasePDA
  id: Security_KnightPDA
  name: КПК Рыцаря Звёздной-пыли
  description: КПК дающий понять что перед вами не обычный сотрудник СБ.
  components:
  - type: PDA
    id: SecurityIDCard #Security_KnightIDCard
    state: pda-knight
  - type: Icon
    state: pda-knight

- type: entity
  parent: ClothingOuterStorageBase
  id: ClothingOuterCoatKnight
  name: Пальто Звёздной-пыли
  description: Легендарное пальто безарного война, говорят именно в нём первый рыцарь звёздной пыли прибыл на станцию.
  components:
  - type: Sprite
    sprite: FireStation/Clothing/Knight/coat.rsi
  - type: Clothing
    sprite: FireStation/Clothing/Knight/coat.rsi
  - type: StorageFill
    contents:
    - id: Joint
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.8
        Slash: 0.8
        Piercing: 0.6
        Heat: 0.9

- type: entity
  noSpawn: true
  parent: ClothingBackpackSecurity_Knight
  id: ClothingBackpackSecurity_KnightFilled
  components:
  - type: StorageFill
    contents:
      - id: BoxSurvivalSecurity
      - id: BoxHoloparasiteKnight
      - id: Flash
      - id: HoloprojectorSecurity

- type: entity
  parent: ClothingBackpack
  id: ClothingBackpackSecurity_Knight
  name: security backpack
  description: It's a very robust backpack.
  components:
  - type: Sprite
    sprite: FireStation/Clothing/Knight/backpack.rsi
  - type: Storage
    capacity: 200

- type: entity
  parent: ClothingHeadBaseButcherable
  id: ClothingHeadHelmetHelmetKnight
  name: Кепка Звёздной-пыли
  description: Один вид этой бизарной кепки, даёт понять напротив стоящему человеку, с кем он имеет дело.
  components:
  - type: Sprite
    sprite: Clothing/Head/Soft/bizarresoft.rsi
  - type: Clothing
    sprite: Clothing/Head/Soft/bizarresoft.rsi
  - type: Armor
    modifiers:
      coefficients:
        Blunt: 0.8
        Slash: 0.8
        Piercing: 0.9
        Heat: 0.8

- type: entity
  parent: ClothingUniformBase
  id: ClothingUniformJumpsuitKnight
  name: Костюм Звёздной-пыли
  description: Одежда рыцаря, чей только вид даёт понять кто стоит перед тобой.
  components:
  - type: Sprite
    sprite: FireStation/Clothing/Knight/jumpsuit.rsi
  - type: Clothing
    sprite: FireStation/Clothing/Knight/jumpsuit.rsi

- type: entity
  name: Коробка Рыцаря Звёздной-пыли
  parent: BoxCardboard
  id: BoxHoloparasiteKnight
  description: A box containing a holoparasite injector
  components:
  - type: StorageFill
    contents:
      - id: HoloparasiteInjectorKnight
      - id: HoloparasiteInfo
  - type: Sprite
    layers:
      - state: box
      - state: holo

- type: entity
  name: Инжектор Звёздной-пыли
  id: HoloparasiteInjectorKnight
  parent: BaseItem
  description: A complex artwork of handheld machinery allowing the user to host a holoparasite guardian.
  components:
  - type: Sprite
    sprite: Objects/Specific/Medical/hypospray.rsi
    state: combat_hypo
    netsync: false
  - type: GuardianCreator
    guardianProto: MobHoloparasiteGuardianK

- type: entity
  parent: ClothingUniformSkirtBase
  id: ClothingUniformJumpskirtKnight
  name: Юбка Звёздной-пыли
  description: "Одежда рыцаря, чей только вид даёт понять кто стоит перед тобой."
  components:
  - type: Sprite
    sprite: FireStation/Clothing/Knight/jumpskirt.rsi
  - type: Clothing
    sprite: FireStation/Clothing/Knight/jumpskirt.rsi
