- type: playTimeTracker
  id: JobSCPScientist

- type: playTimeTracker
  id: JobSCPSecurity

- type: playTimeTracker
  id: JobSCPHead

- type: playTimeTracker
  id: JobSCPDClass

- type: playTimeTracker
  id: JobSecurityKnight
